# Generated by Django 5.2.5 on 2025-08-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(),
        ),
    ]
